### ISSUE TITLE
TypeError: $(...).dropdown is not a function

### ISSUE THREAD

**Issue by gapipro** [CroudSupport/vue-semantic#1]
Hi,

so I am trying to use your components but when I want to render a dropdown I get following error. 

`TypeError: $(...).dropdown is not a function
`
It looks like semantic.js was never loaded but I added it to head of page. 

Am I missing something else?

**Comment by BrockReece** [comment]
Hi,

I presume you have added jQuery to the top of your page too?

Cheers
Brock

**Comment by gapipro** [comment]
Yes,  jQuery and semantic are both added.

Do you maybe have a sample project of usage?

**Comment by BrockReece** [comment]
No I don't have a sample project.
Are you using webpack or browserify?

**Comment by BrockReece** [comment]
https://jsfiddle.net/saytnzdf/1/
Here is a quick fiddle that loads semantic, jquery and builds a dropdown

**Comment by gapipro** [comment]
I am using webpack.

What I noticed is that if I do $('.dropdown').dropdown from console it
works, but if I do a breakpoint in your script then $ is just plain jQuery
without any plugins attached.

**Comment by BrockReece** [comment]
I am using webpack too.
I import the semantic js file at the top of my main.js 

``` js
import 'path/to/semantic'
```

And I load my jquery in the webpack.base.conf.js like so...

``` js
plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery"
    })
  ],
```

Do you have a similar setup?

**Comment by gapipro** [comment]
Ok, got it working by importing semantic js file inside a main.js. 

Before I loaded it as normal script in template file same as jQuery. 

Ty

**Comment by BrockReece** [comment]
No problem

**Comment by manjudr** [comment]
@gapipro  Even I am also facing the same issue


```js
new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            _: 'lodash',
            async: 'async'
        }),

```

Is there any fix using web pack without modifying the project core files 

@BrockReece
