### ISSUE TITLE
formDropdown - Options watcher will unselect items when fired

### ISSUE THREAD

**Issue by kingy04** [CroudSupport/vue-semantic#20]
If you set multiple: true and useLabels: false, this watcher clears the selected items from the dropdown selected summary when fired, then re-adds them when fired again and so on..

**Comment by BrockReece** [comment]
This watcher can be bypassed using the `:auto-update="false"` prop
Does that fix the issue?

**Comment by BrockReece** [comment]
Oh sorry the Options watcher... are you sure that is the watcher that is being triggered?
What is changing in your options object? Have you got an example?
