### ISSUE TITLE
Add some examples

### ISSUE THREAD

**Issue by jmoren** [CroudSupport/vue-semantic#7]
Please add examples how to use the different components.

**Comment by oytunyuksel** [comment]
+1

**Comment by bogdandevlpr** [comment]
+1

**Comment by ErwanLent** [comment]
+1 doooo it

**Comment by gandoo** [comment]
+1

**Comment by BrockReece** [comment]
Sorry I have been quite busy lately.
I will add some example soon.

**Comment by Shashwatsh** [comment]
+1

**Comment by saleh-old** [comment]
+1

**Comment by ghost** [comment]
any news ?

**Comment by BrockReece** [comment]
Hi everyone,

Once again, huge apologies for how slowly this has moved.
I have started generating a style guide using [styleguidist](https://github.com/vue-styleguidist/vue-styleguidist)

First version is up on github pages http://croudsupport.github.io/vue-semantic/

I will be adding to this over the next week so feel free to make suggestions or even contribute if you want.

Thanks for your patience.
Brock

**Comment by ErwanLent** [comment]
Fantastic! Thank you!
